workflows:
  ios-debug-build:
    name: iOS Unsigned Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter doctor and clean
        script: |
          cd word_world_quiz
          flutter doctor
          flutter clean
      - name: Get Flutter dependencies
        script: |
          cd word_world_quiz
          flutter packages pub get
      - name: Build iOS Debug App
        script: |
          cd word_world_quiz
          flutter build ios --debug --no-codesign
    artifacts:
      - word_world_quiz/build/ios/iphoneos/*.app